#! /usr/bin/env bash
set -euo pipefail

color_green='\033[0;32m'
color_yellow='\033[0;33m'
color_cyan='\033[0;36m'
color_none="\033[0m"

echo_green() {
  echo -e "${color_green}${1:-}${color_none}"
}

echo_yellow() {
  echo -e "${color_yellow}${1:-}${color_none}"
}

echo_cyan() {
  echo -e "${color_cyan}${1:-}${color_none}"
}

echo_command() {
  local cmd="$1"
  echo_yellow "$cmd"
  eval "$cmd"
}
