baseURL = "https://andywhite.xyz/"
title = "Andy White"
languageCode = "en-us"
theme = "hugo-coder"

# Site generation
enableRobotsTXT = true
paginate = 20
canonifyurls = true

# Code blocks
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Emoji
enableEmoji = true

# Sitemap settings (not sure if this is hugo core or theme-driven?)
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# hugo-coder theme settings
[params]
  author = "Andy White"
  info = "Full stack developer and fan of typed functional programming"
  description = "Andy White's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/andy.jpeg"
  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"
  footercontent = ""
  hidecredits = true
  hidecopyright = true
  rtl = false
  math = true
  custom_css = []
  inverted = false
[[params.social]]
  name = "GitHub"
  icon = "fab fa-github fa-2x"
  weight = 1
  url = "https://github.com/andywhite37"
[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/whitehouse3001"
[[menu.main]]
  name = "Blog"
  weight = 1
  url = "/blog/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "/projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "/about/"