#! /usr/bin/env bash
set -euo pipefail

. ./bash_common

echo_green "Deploying updates to GitHub pages..."

./clean_public

# Build site to public/ (with drafts on for now)
echo_cyan "Building site..."
echo_command "hugo"

# Commit and push the site to the submodule
echo_cyan "Pushing public/ folder..."
echo_command "cd public"
echo_command "git add -A"
echo_command "git commit -m 'Site deployment'"
echo_command "git push origin master"

# Now update the root repo to get the submodule ref
echo_cyan "Updating root repo..."
echo_command "cd .."
echo_command "git add -A"
echo_command "git commit -m 'Site deployment'"
echo_command "git push"

echo_green "Done!"